// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQeLXDO2pdrQvvtK4T1Ym9QnXZA3cP84o',
    appId: '1:423426972348:web:753f19fd92f2e7b8ad0eb9',
    messagingSenderId: '423426972348',
    projectId: 'login17-8e2e8',
    authDomain: 'login17-8e2e8.firebaseapp.com',
    storageBucket: 'login17-8e2e8.firebasestorage.app',
    measurementId: 'G-6GVPGSZXD8',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WPeQlvijWm3WILEX3H-aj9Q7Kcrjhq8',
    appId: '1:423426972348:android:706dca7e7b750c5bad0eb9',
    messagingSenderId: '423426972348',
    projectId: 'login17-8e2e8',
    storageBucket: 'login17-8e2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWIPdrf7plG7goEGkD5KcxfClOAHu9Ijw',
    appId: '1:423426972348:ios:c38866329c786facad0eb9',
    messagingSenderId: '423426972348',
    projectId: 'login17-8e2e8',
    storageBucket: 'login17-8e2e8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWIPdrf7plG7goEGkD5KcxfClOAHu9Ijw',
    appId: '1:423426972348:ios:c38866329c786facad0eb9',
    messagingSenderId: '423426972348',
    projectId: 'login17-8e2e8',
    storageBucket: 'login17-8e2e8.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQeLXDO2pdrQvvtK4T1Ym9QnXZA3cP84o',
    appId: '1:423426972348:web:22e169c8626058aead0eb9',
    messagingSenderId: '423426972348',
    projectId: 'login17-8e2e8',
    authDomain: 'login17-8e2e8.firebaseapp.com',
    storageBucket: 'login17-8e2e8.firebasestorage.app',
    measurementId: 'G-7NMTFX2W4V',
  );
}
